# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
# uncomment the following lines to override the default test script
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd()); Pkg.build("KeyedFrames"); Pkg.test("KeyedFrames"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("KeyedFrames"))
      Pkg.add("KeyedFrames"); using Coverage
      Codecov.submit(process_folder())'
