# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0  # LTS
  - 1.3  # Current release
  - nightly
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true

  include:
    - stage: "Documentation"
      julia: 1
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

notifications:
  email:
    recipients:
      - nightly-dev@invenia.ca
    on_success: never
    on_failure: always
    if: type = cron

after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
